### PR TITLE
Refactoring pull request

### PR DESCRIPTION
**Pull request by varky**
Hi,
As discussed on reddit, I've tried refactoring the project a bit. I've not tested it, as I unfortunately don't have a proxmox machine, but at least the syntax checks pass.

In general, I've pulled all the playbooks into document root for a flatter structure (removes the need for "../../" designations when referencing files and templates), with some changes in the playbooks themselves (a bit of formatting, and removing some lines that were moved into the configuration). 
The new ansible.cfg has the default settings for most things, so "become: " designations and similar were removed from playbooks.
The vars file was split into multiple separate vars files for each specific playbook, and stored in the vars directory. I've re-done the general part of the vars files, primarily the node creation parameters, to use a directory instead of individual variables - should make it easily configurable, but also simpler to maintain with defaults being referenced where possible.

If you have the time, I'd appreciate it if you could test it. I'm very well aware some things might not work, but until I can boot a working proxmox machine, I can't test it all myself.

Any issues you find feel free to contact me.

BR,

Ivan

### CODE REVIEW

**Comment by vazhnov** [comment]
Code structure looks better after your change, @varky!

**Comment by zimmertr** [comment]
Hi, sorry for the delay. I've been a little burned out lately and have been ignoring this project. 

I really appreciate the work you did here @varky but to be honest I'm having a little bit of trouble seeing why this file structure is preferred. Here are some comments on your changes. Could you, @varky, and anyone else comment on why you prefer these changes? 





> I've pulled all the playbooks into document root for a flatter structure 

I'm not sure that a flat structure is a better approach. From an aesthetic perspective, at least, I think it makes the repository look more cluttered at first glance and less organized with a deeper look.

> with some changes in the playbooks themselves 

The diff is hard to find many changes because of the files that were moved around but it looks like the only changes made to the playbooks were references to the new locations of the playbooks. Is that so?

> The new ansible.cfg has the default settings for most things

I can get behind this one. Thanks for showing me this. At the very least I would be willing to merge this in. 

> The vars file was split into multiple separate vars files for each specific playbook

Is this considered best practices for Ansible? I suppose I learned Ansible organically instead of by-the-book which is why I might prefer the hierarchal directory structure as well. To me, it also seems preferred to have all of the variables centralized for minimalism and ease of use. 

> I've re-done the general part of the vars files, primarily the node creation parameters, to use a directory instead of individual variables - should make it easily configurable, but also simpler to maintain with defaults being referenced where possible.

Can you please elaborate on how the changes you made make it more configurable and easier to maintain? Once again, my Ansible-fu wasn't learned by reading documentation so there's probably something I'm missing here. 

Once again I wanted to thank you for doing all of this work and opening the PR. I just need some clarification (for my sake) before I merge it in to understand exactly why these changes are an improvement. To me, most of them just seem like another person's opinion how things should be done that I find, in some ways, disagreeable. But it pretty much exclusively pertains to personal preference in these situations.

**Comment by zimmertr** [comment]
Hi, sorry for the delay. I've been a little burned out lately and have been ignoring this project. 

I really appreciate the work you did here @varky but to be honest I'm having a little bit of trouble seeing why this file structure is preferred. Here are some comments on your changes. Could you, @vazhnov, and anyone else comment on why you prefer these changes? And maybe link me to some Ansible documentation explaining why these decisions are an improvement?

> I've pulled all the playbooks into document root for a flatter structure 

I'm not sure that a flat structure is a better approach. From an aesthetic perspective, at least, I think it makes the repository look more cluttered at first glance and less organized with a deeper look.

> with some changes in the playbooks themselves 

The diff is hard to find many changes because of the files that were moved around but it looks like the only changes made to the playbooks were references to the new locations of the playbooks. Is that so?

> The new ansible.cfg has the default settings for most things

I can get behind this one. Thanks for showing me this. At the very least I would be willing to merge this in. 

> The vars file was split into multiple separate vars files for each specific playbook

Is this considered best practices for Ansible? I suppose I learned Ansible organically instead of by-the-book which is why I might prefer the hierarchal directory structure as well. To me, it also seems preferred to have all of the variables centralized for minimalism and ease of use. 

> I've re-done the general part of the vars files, primarily the node creation parameters, to use a directory instead of individual variables - should make it easily configurable, but also simpler to maintain with defaults being referenced where possible.

Can you please elaborate on how the changes you made make it more configurable and easier to maintain? Once again, my Ansible-fu wasn't learned by reading documentation so there's probably something I'm missing here. 

Once again I wanted to thank you for doing all of this work and opening the PR. I just need some clarification (for my sake) before I merge it in to understand exactly why these changes are an improvement. To me, most of them just seem like another person's opinion how things should be done that I find, in some ways, disagreeable. But it pretty much exclusively pertains to personal preference in these situations.

**Comment by zimmertr** [comment]
This has been open for 3 months without any movement and is now quite a bit beyond after adding support for Buster. Feel free to reopen in the future if you want.

**Pull request closed without merging**
